query Articles {
  articles {
    id
    title
    published_at
    updated_at
    content

    image {
      name
      url
      formats
      previewUrl
    }
    categories {
      name
      id
    }
  }
}
